### ISSUE TITLE
Search for presets in system directory /usr/share/aubibleplanets/presets

### ISSUE THREAD

**Issue by ycollet** [gregrecco67/AudiblePlanets#1]
Is it possible to add the following search presets directory:
Search for presets in system directory /usr/share/aubibleplanets/presets

This will allow to install some presets found in https://github.com/gregrecco67/Audible-Planets-Presets in the package installed by the user.
After that, users will be still be able to install custom presets in ~/.config/com.void-star/Audible Planets/programs.

I added your plugin in the following fedora repository:
https://copr.fedorainfracloud.org/coprs/ycollet/audinux/

**Comment by gregrecco67** [comment]
Thank you. Preset browsing is provided by the Gin library, and the preset locations ultimately depend on `juce::File::userApplicationDataDirectory`, which seems like the appropriate choice here. That said, I hope to provide a cleaner "built-in" preset system in the future.

**Comment by ycollet** [comment]
Thank !
