### ISSUE TITLE
Version 1.1.0 fails to scan on REAPER 7.18, Windows 11

### ISSUE THREAD

**Issue by Someone65** [gregrecco67/AudiblePlanets#10]
The version before this scans successfully but 1.1.0 fails to scan properly. It outright crashes REAPER if you try to load it from if you had previously scanned its older version successfully but update it by replacing the file.

**Comment by gregrecco67** [comment]
I just updated to 7.18 and confirmed I was using the plugin downloaded from the Releases page and could not replicate this error on Windows 11 using either the VST3 or LV2 version.

**Comment by Someone65** [comment]
I tried installing 1.0.22 and it's not crashing so something changed between these versions that's causing this.

**Comment by gregrecco67** [comment]
For version 1.1, the underlying framework, JUCE, was updated to version 8. Other than that, the only significant changes were to the UI layout, so you're not missing out on any new functionality if you stick to an older version that works. That said, you might try the 1.1.1 LV2 plugin in Reaper. If you find any crash report in Windows Event Viewer, that might give me some more information, but without being able to reproduce the bug, I'm unlikely to be able to fix it.

**Comment by Someone65** [comment]
I checked the event viewer and saw it was something to do with VC Redist, so I repaired my VCRedist install and restarted my PC and that apparently just fixed it.
