### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by STOP63** [gregrecco67/AudiblePlanets#11]
Dear Planets Developer,

I wanted to inform you that all versions starting from 1.1 have issues in the DAW Reaper. The VST3 version does not appear in the plugin list, and the LV2 version crashes Reaper.
Version 1.0.22 seems to work, but I am still testing and exploring it.

Reaper 7.18
Windows 11 23H2
Dell 12th Gen Intel(R) Core(TM) i3-12100   3.30 GHz

Thank you for your attention to this matter.

Best regards,
Etienne Lauzon

**Comment by gregrecco67** [comment]
Hello, and thanks for reporting. I'm on the same versions of Windows and Reaper (but with a different processor) and can't reproduce this error. Another user reported a similar problem and was able to resolve it by repairing their system's Visual C++ Redistributable. If that doesn't work, information from the crash log in Event Viewer would be useful.

**Comment by STOP63** [comment]
«Another user reported a similar problem and was able to resolve it by repairing their system's Visual C++ Redistributable.»

That was it, I reinstalled the latest Microsoft Visual C++ Redistributable version, and now it works.

I think the issue comes from some plugins reinstalling a different version of the latest Visual C++ Redistributable during their installation, which breaks it.

Thank you for your excellent and original synth plugin.

**Comment by gregrecco67** [comment]
Thanks for the kind words. Glad it worked!
