### ISSUE TITLE
New update still crashes Ableton Live Suite 10.1.4/Catalina OS

### ISSUE THREAD

**Issue by irish-moss** [gregrecco67/AudiblePlanets#12]
Hi Greg, 

I've tried to no avail to use this rather nice looking synth with both release versions. As soon as I drag it into Ableton, it has a fatal crash and shuts the DAW down. 
I'd love to help sort this with you if need be.
My email is dreadlion13@gmail.com 
Thank you! 
Rob

**Comment by gregrecco67** [comment]
I've update the Mac binary releases (1.1.4a) to be compatible with Catalina (10.15.4) on Intel, at least. If you have an Apple Silicon chip, you would need to upgrade to Big Sur. Can you download the latest and give it a try?

**Comment by irish-moss** [comment]
It's working now Greg! Great work. Look forward to exploring it
Rob

**Comment by irish-moss** [comment]
It's working now Greg! Great work. Look forward to exploring it
Rob

**Comment by gregrecco67** [comment]
Glad to hear it!

**Comment by irish-moss** [comment]
The component did get the beachball of death tho when scolling presets while playing, I walked away as it spun and Live crashed. I'm going to try the vst3 now and see if there is a difference.

**Comment by irish-moss** [comment]
Definitely getting there!

**Comment by irish-moss** [comment]
Ok VST3 crashed while changing settings with transport running. But you're very close here!!

**Comment by gregrecco67** [comment]
Good news and bad news. I was able to reproduce the crashes on an Intel mac and then fix them. Bad news: I had to bump up the deployment target to Monterey (12.0) to get this result. I hope you are able to upgrade from Catalina, which the JUCE 8 framework does not support.

**Comment by irish-moss** [comment]
I actually cannot upgrade on this older computer man. In 2014 this thing
was an 8k computer LOL. That's the way she goes :)
Thanks for trying though. Hope input helped.
Rob

**Comment by gregrecco67** [comment]
Sorry to hear it. In my testing, I found it was UI interactions that provoked crashes and other bugs in the version built for Catalina, and in particular closing and then reopening the editor window. And again, thank you for the report; it was helpful.

**Comment by irish-moss** [comment]
Yea I realize at some point there isn't much you can do.

Do you know how to build a MIDI breakout box? I've been conceiving a M4L
one that allows any midi signal to be sent and received/split to anywhere
on the Live matrix.
I'm also trying to imagine one that works with DRUM RACK to easily route
drum audio to split sums better.
I'm an artist with a lot of years of Live and Max but haven't been able to
take the time away from creating music to focus on how M4L building is
done. I lightly observe it and then go ok, maybe over your head lol
Rob

**Comment by irish-moss** [comment]
Yea I realize at some point there isn't much you can do. Do you know how to
build a MIDI breakout box? I've been conceiving a M4L one that allows any
midi signal to be sent and received/split to anywhere on the Live matrix.
I'm also trying to imagine one that works with DRUM RACK to easily route
drum audio to split sums better. I'm an artist with a lot of years of Live
and Max but haven't been able to take the time away from creating music to
focus on how M4L building is done. I lightly observe it and then go ok,
maybe over your head lol Rob

**Comment by irish-moss** [comment]
I'm 52 and on disability pension. I create all day. I'd love to help you
develop some devices and test for you if you would like.
I have done it in the past for designers. I have a background in playing
actual instruments, composition, engineering and sound design.
I've worked on the dvd features for The Fountain, The Wrestler and The
Black Swan for Darren Aronofsky, WB/FOX

Let me know! I find it fun
Rob

**Comment by irish-moss** [comment]
I tried to write you directly, the other day on email. It posted here and I realized it wasn't the place for one on one. In short, I have time to help test devices if you should need someone. dreadlion13@gmail.com - Rob

**Comment by gregrecco67** [comment]
OK, thank you.
