### ISSUE TITLE
Not showing

### ISSUE THREAD

**Issue by rudo56** [gregrecco67/AudiblePlanets#2]
I am on macos, intel. 
Not working on Logic.
Not in Ableton
Codesign them doesnt help. 
Not AU, Not VST3.

**Comment by gregrecco67** [comment]
Not sure what's going wrong. I only have access to an arm64 Mac atm, but it passes validation here and the binaries for at least 1.0.8 and 1.0.9 are for both architectures. Can you run the Plug-in Manager in Logic and see what it says? If it's not showing in the Plug-in Manager, maybe it's not installed in the directory where the DAWs are looking for it. Also, I code-signed the most recent binaries, fwiw.

**Comment by rudo56** [comment]
The directory is the standard. 
Logic validation says:
validating Audio Unit Audible Planets by Void-Star:

    AU Validation Tool
    Version: 1.10.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'APts' - 'Vdst'
--------------------------------------------------
Manufacturer String: Void-Star
AudioUnit Name: Audible Planets
Component Version: 1.0.8 (0x10008)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF

**Comment by rudo56** [comment]
It is not asking to notarization. I don't get why you have to notarize on intel and not in arm.
[https://melatonin.dev/blog/how-to-code-sign-windows-installers-with-an-ev-cert-on-github-actions/](url)

Also Chrome is saying the file is suspicious.

**Comment by gregrecco67** [comment]
Have you looked in "Privacy & Security"? Try running `auval -a` in a terminal. Do you get a pop-up warning about "Apple cannot check for malicious software"? That is about notarization. If so, you have the option to "Run Anyway" from the Settings > Privacy & Security pane. Also, try version 1.0.9.

**Comment by rudo56** [comment]
Yes, nothing there. Also in 1.0.9. auval -a no changes at all, no popup. (I have already done this in toher apps that need that, but never with plugins.)
Ableton says: This plugin is deactivated.

**Comment by gregrecco67** [comment]
What's the output of `auval -v aumu APts Vdst`? Or if not the whole output, then the error.

Alternatively, in the Logic plug-in manager, select the plugin and try "Reset & Rescan Selection".

**Comment by rudo56** [comment]
Output:

auval -v aumu APts Vdst

    AU Validation Tool
    Version: 1.10.0
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'APts' - 'Vdst'
--------------------------------------------------
Manufacturer String: Void-Star
AudioUnit Name: Audible Planets
Component Version: 1.0.9 (0x10009)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF

**Comment by rudo56** [comment]
"Reset & Rescan Selection" same result as the code:

validating Audio Unit Audible Planets by Void-Star:

    AU Validation Tool
    Version: 1.10.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aumu' - 'APts' - 'Vdst'
--------------------------------------------------
Manufacturer String: Void-Star
AudioUnit Name: Audible Planets
Component Version: 1.0.9 (0x10009)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF


validation result: no se ha podido abrir

**Comment by rudo56** [comment]
Yes both included
`file /Library/Audio/Plug-Ins/Components/Audible\ Planets.component/Contents/MacOS/Audible\ Planets
/Library/Audio/Plug-Ins/Components/Audible Planets.component/Contents/MacOS/Audible Planets: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64]
/Library/Audio/Plug-Ins/Components/Audible Planets.component/Contents/MacOS/Audible Planets (for architecture x86_64):	Mach-O 64-bit bundle x86_64
/Library/Audio/Plug-Ins/Components/Audible Planets.component/Contents/MacOS/Audible Planets (for architecture arm64):	Mach-O 64-bit bundle arm64`

**Comment by gregrecco67** [comment]
I was able to reproduce the error with another plugin, even getting the same error code. It looks like it's the quarantine attribute. Try this:
`sudo xattr -r -d com.apple.quarantine /Users/grecco/Library/Audio/Plug-Ins/Components/Audible\ Planets.component`
I got a popup from this, too. But afterwards, when I ran "Reset & Rescan Selection" in Logic Pro, it passed validation.

**Comment by rudo56** [comment]
Users/Grecco/?
It is the same, no diff.

**Comment by gregrecco67** [comment]
or just `xattr -c` etc.

**Comment by gregrecco67** [comment]
sorry, I mean with the location of the plugin on your machine

**Comment by gregrecco67** [comment]
so `xattr -c ~/Library/Audio/Plug-ins/Components/Audible\ Planets.component/`

**Comment by rudo56** [comment]
I did the ussual xattr - c, codesign etc
Nothing

**Comment by gregrecco67** [comment]
OS version?

**Comment by rudo56** [comment]
Latest ventura

**Comment by rudo56** [comment]
Should be something else, cos' no vst, no vst3 also. And in any daw i try

**Comment by gregrecco67** [comment]
Let me try rebuilding with a different deployment target.

**Comment by rudo56** [comment]
Cool, I'll check

**Comment by gregrecco67** [comment]
just published as 1.0.9a. Hope it works. Let me know!
