### ISSUE TITLE
clap plugin

### ISSUE THREAD

**Issue by RustoMCSpit** [gregrecco67/AudiblePlanets#4]
hi! you already support lv2 and vst3, will you support clap?

**Comment by gregrecco67** [comment]
hello! I'm afraid that's a little unstable for me at the moment. I'd like to do it in the future, but for now, support for all the plugin formats is coming from JUCE, which is about to do a major version release, and they have not yet implemented support for building CLAP plugins. There's [this](https://github.com/free-audio/clap-juce-extensions) project, which I'd recommend to anyone who wants to try it out and build against it. If after JUCE 8 comes out, and if I switch to it, and if it plays well with this unofficial extension, I will try to offer a CLAP version, too, but that is likely to be 1-2 months away.
