### ISSUE TITLE
AU Failing Validation

### ISSUE THREAD

**Issue by DixonBainbridge** [gregrecco67/AudiblePlanets#9]
I use two different DAWs [Tracktion Waveform and Ableton Live] on MacOS and neither of them recognize the AU/pass validation. The OS says it cannot identify the developer and locks it out in the Security & Privacy prefs.

**Comment by gregrecco67** [comment]
You can authorize it to run from the Security & Privacy settings page or, in the OSX terminal, type sudo xattr -cr then a space and drag the file in the Terminal window (to fill in its path), then give your password when prompted by sudo.
